# Generated by Django 5.2.5 on 2025-09-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_product_extended_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='long_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
