# Generated by Django 5.2.5 on 2025-09-07 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_product_long_description'),
        ('shops', '0007_category_and_product_category_fk'),
    ]

    operations = [
    ]
