# Generated by Django 5.2.5 on 2025-10-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_product_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantoption',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productvarianttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
